apiVersion: batch/v1
kind: Job
metadata:
  name: portable-app-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef: {name: pg-app, key: host, optional: true}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef: {name: pg-app, key: dbname, optional: true}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: {name: pg-app, key: username, optional: true}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: {name: pg-app, key: password, optional: true}
