#!/usr/bin/env python3
"""Render thin per-assistant files from the canonical clean-architecture-guard sources.

Standard library only, Python 3.11+. install.sh calls this; nothing here holds rules.
The rules live in steering/*.md and agents/architecture-reviewer.md, and the checks
live in archguard/archguard.py. Every renderer is deterministic.

Subcommands:
  rules         steering/*.md -> Markdown block for AGENTS.md (Codex, Claude Code)
  block         insert or replace a marked block in a file (AGENTS.md, CLAUDE.md)
  claude-agent  Kiro agent -> .claude/agents/<name>.md
  codex-agent   Kiro agent -> .codex/agents/<name>.toml
  claude-mcp    .mcp.json for Claude Code
  codex-mcp     .codex/config.toml for Codex
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

BEGIN = "<!-- archguard:begin -->"
END = "<!-- archguard:end -->"
SOURCE_TOOLS = "kiro/archguard/"


def split_front_matter(text: str) -> tuple[dict[str, str], str]:
    """Return (flat key: value pairs, body). Only single-line keys are parsed."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.index("\n---\n", 4)
    meta = {}
    for line in text[4:end].splitlines():
        m = re.match(r"^([A-Za-z]\w*):\s*(.*)$", line)
        if m:
            meta[m.group(1)] = m.group(2).strip().strip('"')
    return meta, text[end + 5:].lstrip("\n")


def rewrite_tools(text: str, tools_rel: str) -> str:
    return text.replace(SOURCE_TOOLS, tools_rel.rstrip("/") + "/")


def demote_headings(md: str, levels: int = 1) -> str:
    """Add `levels` '#' to every ATX heading outside fenced code blocks."""
    out, fenced = [], False
    for line in md.splitlines():
        if line.lstrip().startswith("```"):
            fenced = not fenced
        elif not fenced and re.match(r"^#{1,5} ", line):
            line = "#" * levels + line
        out.append(line)
    return "\n".join(out)


def render_rules(steering_dir: Path, tools_rel: str) -> str:
    """AGENTS.md block body: always-on rules, file-scoped rules, and the JSON commands."""
    ag = f"{tools_rel.rstrip('/')}/archguard.py"
    parts = [
        "## Clean architecture guard",
        "",
        "Generated by clean-architecture-guard `install.sh`. Edit the source steering",
        "files and rerun the installer instead of editing this block.",
        "",
    ]
    always, scoped = [], []
    for f in sorted(steering_dir.glob("*.md")):
        meta, body = split_front_matter(f.read_text(encoding="utf-8"))
        body = demote_headings(rewrite_tools(body.strip(), tools_rel), 2)
        if meta.get("inclusion") == "fileMatch":
            pattern = meta.get("fileMatchPattern", "")
            scoped.append(f"Applies when you edit files matching `{pattern}`.\n\n{body}")
        else:
            always.append(body)
    parts += always
    parts += scoped
    parts += [
        "",
        "### Commands with machine-readable output",
        "",
        "Parse JSON, not text. Paths in the output are relative to `archguard.toml`.",
        "",
        "```sh",
        f"python3 {ag} check --format json          # AG001-AG003 violations, exit 1 if any",
        f"python3 {ag} score --format json          # portability and cleanliness scores + findings",
        f"python3 {ag} score --format sarif         # the same findings as SARIF 2.1.0",
        f"python3 {ag} scan <dir> --format json     # classification, boundary map, refactor plan",
        "```",
        "",
        "In `score` JSON, read `scores.portability.score`, `scores.cleanliness.score`, and",
        "`findings[]` (`id`, `rule`, `dimension`, `severity`, `path`, `line`, `message`, `hint`).",
        "Refer to findings by `id`: it stays the same when lines move.",
    ]
    return "\n".join(parts).rstrip() + "\n"


def upsert_block(path: Path, content: str, header: str = "") -> str:
    """Insert or replace the marked block. Text outside the markers is never changed.

    Returns 'created', 'updated' or 'unchanged'.
    """
    block = f"{BEGIN}\n{content.rstrip()}\n{END}\n"
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text((header + "\n\n" if header else "") + block, encoding="utf-8")
        return "created"
    text = path.read_text(encoding="utf-8")
    start, stop = text.find(BEGIN), text.find(END)
    if start == -1 and stop == -1:
        new = text.rstrip("\n") + "\n\n" + block if text.strip() else block
    elif start != -1 and stop > start:
        new = text[:start] + block.rstrip("\n") + text[stop + len(END):]
    else:
        raise ValueError(f"{path}: unbalanced {BEGIN} / {END} markers; fix them by hand")
    if new == text:
        return "unchanged"
    path.write_text(new, encoding="utf-8")
    return "updated"


def _agent_parts(kiro_agent: Path, tools_rel: str) -> tuple[dict[str, str], str]:
    meta, body = split_front_matter(kiro_agent.read_text(encoding="utf-8"))
    body = rewrite_tools(body, tools_rel)
    # The Kiro prompt names Kiro-only features; say what they are in other hosts.
    body = body.replace("suggest switching to the default agent", "suggest handing the work to the main agent")
    return meta, body.rstrip() + "\n"


def render_claude_agent(kiro_agent: Path, tools_rel: str) -> str:
    """Claude Code subagent: no write tools (allowlist plus disallowedTools).

    Bash stays available so the agent can run archguard; the prompt limits it to
    archguard commands. That limit is an instruction, not a sandbox.
    """
    meta, body = _agent_parts(kiro_agent, tools_rel)
    return (
        "---\n"
        f"name: {meta['name']}\n"
        f"description: {json.dumps(meta['description'])}\n"  # a JSON string is valid YAML
        "tools: Read, Grep, Glob, Bash, mcp__archguard__archguard_scan, "
        "mcp__archguard__archguard_check, mcp__archguard__archguard_score\n"
        "disallowedTools: Write, Edit, MultiEdit, NotebookEdit\n"
        "---\n"
        "<!-- Generated by clean-architecture-guard install.sh from agents/architecture-reviewer.md. -->\n"
        f"{body}"
    )


def toml_string(s: str) -> str:
    # A JSON string with ensure_ascii is a valid TOML basic string.
    return json.dumps(s, ensure_ascii=True)


def render_codex_agent(kiro_agent: Path, tools_rel: str) -> str:
    """Codex custom agent: read-only sandbox, the same prompt as the Kiro agent."""
    meta, body = _agent_parts(kiro_agent, tools_rel)
    name = meta["name"].replace("-", "_")
    return (
        "# Generated by clean-architecture-guard install.sh from agents/architecture-reviewer.md.\n"
        f"name = {toml_string(name)}\n"
        f"description = {toml_string(meta['description'])}\n"
        'sandbox_mode = "read-only"\n'
        f"developer_instructions = {toml_string(body)}\n"
    )


def render_claude_mcp(script: str) -> str:
    data = {"mcpServers": {"archguard": {"type": "stdio", "command": "python3", "args": [script]}}}
    return json.dumps(data, indent=2) + "\n"


def render_codex_mcp(script: str) -> str:
    return (
        "# Generated by clean-architecture-guard install.sh. Codex loads project config\n"
        "# only for trusted projects.\n"
        "[mcp_servers.archguard]\n"
        'command = "python3"\n'
        f"args = [{toml_string(script)}]\n"
        'enabled_tools = ["archguard_scan", "archguard_check", "archguard_score"]\n'
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="render.py")
    sub = p.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("rules")
    r.add_argument("steering_dir", type=Path)
    r.add_argument("tools_rel")
    r.add_argument("out", type=Path)
    b = sub.add_parser("block")
    b.add_argument("target", type=Path)
    b.add_argument("content", type=Path)
    b.add_argument("--header", default="")
    for name in ("claude-agent", "codex-agent"):
        a = sub.add_parser(name)
        a.add_argument("kiro_agent", type=Path)
        a.add_argument("tools_rel")
        a.add_argument("out", type=Path)
    for name in ("claude-mcp", "codex-mcp"):
        m = sub.add_parser(name)
        m.add_argument("script")
        m.add_argument("out", type=Path)
    args = p.parse_args(argv)
    try:
        if args.cmd == "rules":
            args.out.write_text(render_rules(args.steering_dir, args.tools_rel), encoding="utf-8")
        elif args.cmd == "block":
            status = upsert_block(args.target, args.content.read_text(encoding="utf-8"), args.header)
            print(status)
        elif args.cmd == "claude-agent":
            args.out.write_text(render_claude_agent(args.kiro_agent, args.tools_rel), encoding="utf-8")
        elif args.cmd == "codex-agent":
            args.out.write_text(render_codex_agent(args.kiro_agent, args.tools_rel), encoding="utf-8")
        elif args.cmd == "claude-mcp":
            args.out.write_text(render_claude_mcp(args.script), encoding="utf-8")
        elif args.cmd == "codex-mcp":
            args.out.write_text(render_codex_mcp(args.script), encoding="utf-8")
    except (OSError, ValueError, KeyError) as exc:
        sys.stderr.write(f"render.py: {exc}\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
