#!/bin/bash
# Provision the two DynamoDB tables used by the DynamoDB repository adapters.
#
# The tables are shared by every runtime (Lambda, ECS, EKS). This is what
# enables the shared-state proof in the talk: create a user through the Lambda
# endpoint, read it back through the EKS endpoint, same record.
#
# Table design is intentionally minimal: one partition key "id" (String),
# on-demand capacity, no GSIs. It mirrors the in-memory adapter (a dict keyed
# by id) and nothing more.
#
# Outputs (git-ignored, consumed by the deploy scripts):
#   codetalk_deployment/.dynamodb_tables     exports DYNAMODB_USERS_TABLE,
#                                             DYNAMODB_ORDERS_TABLE, ARNs
#
# Usage:
#   ./create-tables.sh                       # prefix clean-architecture
#   TABLE_PREFIX=demo ./create-tables.sh     # demo-users, demo-orders
set -euo pipefail

AWS_REGION="${AWS_REGION:-us-west-2}"
TABLE_PREFIX="${TABLE_PREFIX:-clean-architecture}"
USERS_TABLE="${TABLE_PREFIX}-users"
ORDERS_TABLE="${TABLE_PREFIX}-orders"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/../.dynamodb_tables"

AWS_ACCOUNT_NUMBER=$(aws sts get-caller-identity --query 'Account' --output text 2>/dev/null || true)
if [ -z "$AWS_ACCOUNT_NUMBER" ]; then
    echo "Unable to get AWS account number. Check your AWS credentials."
    exit 1
fi

echo "Provisioning DynamoDB tables"
echo "  Region: ${AWS_REGION}"
echo "  Tables: ${USERS_TABLE}, ${ORDERS_TABLE}"
echo ""

create_table() {
    local name="$1"
    if aws dynamodb describe-table --table-name "${name}" --region "${AWS_REGION}" &>/dev/null; then
        echo "Table ${name} already exists, skipping create"
    else
        echo "Creating table ${name}..."
        aws dynamodb create-table \
            --table-name "${name}" \
            --attribute-definitions AttributeName=id,AttributeType=S \
            --key-schema AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --tags Key=project,Value=sample-portable-app Key=managed-by,Value=create-tables.sh \
            --region "${AWS_REGION}" \
            --output text --query 'TableDescription.TableStatus'
    fi
    echo "Waiting for ${name} to become ACTIVE..."
    aws dynamodb wait table-exists --table-name "${name}" --region "${AWS_REGION}"
}

create_table "${USERS_TABLE}"
create_table "${ORDERS_TABLE}"

USERS_TABLE_ARN=$(aws dynamodb describe-table --table-name "${USERS_TABLE}" --region "${AWS_REGION}" --query 'Table.TableArn' --output text)
ORDERS_TABLE_ARN=$(aws dynamodb describe-table --table-name "${ORDERS_TABLE}" --region "${AWS_REGION}" --query 'Table.TableArn' --output text)

cat > "${OUTPUT_FILE}" <<EOF
# Generated by codetalk_deployment/dynamodb/create-tables.sh - do not commit
export DYNAMODB_USERS_TABLE="${USERS_TABLE}"
export DYNAMODB_ORDERS_TABLE="${ORDERS_TABLE}"
export DYNAMODB_USERS_TABLE_ARN="${USERS_TABLE_ARN}"
export DYNAMODB_ORDERS_TABLE_ARN="${ORDERS_TABLE_ARN}"
EOF

echo ""
echo "Tables are ACTIVE."
echo "  ${USERS_TABLE_ARN}"
echo "  ${ORDERS_TABLE_ARN}"
echo ""
echo "Wrote ${OUTPUT_FILE}. The Lambda, ECS and EKS deploy scripts source it"
echo "and switch the app to REPOSITORY_BACKEND=dynamodb automatically."
echo ""
echo "Teardown: ./delete-tables.sh"
